### ISSUE TITLE
Stuck on Loading 10%

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#1]
Hi Team,

We just found that almost our player have problem when opening the game and stuck on the loading at 10%

Please kindly check it out and fix it

**Comment by MattheusRossopIII** [comment]
Investigating the issue.

**Comment by ErwinGL1** [comment]
Thanks @MattheusRossopIII , I have checked it out and everything is running well now
