### ISSUE TITLE
Re-connecting issue in match play

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#10]
Hi, we just got a feedback about match play or normal play in our server, if they are playing with A.I. or Bot, they won't re-connect when the game crash or disconnected. But if the game was played with another player, we still can re-join the game and continue to play.

Is it possible to make the player can re-connect or re-join the game even if playing with A.I or Bot?

**Comment by cgore16** [comment]
Hi, its not possible to reconnect when playing against a bot. If there is only one user playing and that person leaves (disconnects) then the room shuts down,

**Comment by farahliany** [comment]
closed, game not designed this way
