### ISSUE TITLE
[FEATURE] Shot Button

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#14]
Hi team,

We just realize that the shot button at right corner for this new update is back to the middle screen again, can you help us with this issue? The player prefer the shot can be perform at right corner like the last build before this..

Thanks,
Erwin

**Comment by MattheusRossopIII** [comment]
Hi Erwin,

I've uploaded 1.0.14g to your beta channel, it has the fix for the shot button position. Please can you test and verify everything is okay on this build?

**Comment by ErwinGL1** [comment]
Thanks Matt, It's all done~
