### ISSUE TITLE
[BUG] In-App Purchase

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#16]
Hi team,

Last night we got a report in iOS version that when he want to purchase the "Ultimate Pack" but it got message "You're out of Cash! Visit the shop to get some more!" (Please refer to the screenshots attached below).

Why this is occured? When we try on TestFlight, it was running well. Hope you can help check this out.

Thanks,
Erwin

![img-20171012-wa0020](https://user-images.githubusercontent.com/31034413/31528475-a2bf8446-affd-11e7-87da-c5ba8628dd01.jpg)
![img-20171012-wa0016](https://user-images.githubusercontent.com/31034413/31528473-9f8504d6-affd-11e7-9a14-671dd8c1b195.jpg)

**Comment by MattheusRossopIII** [comment]
Could not recreate this issue, has there been other reports of this issue?

**Comment by farahliany** [comment]
This issue has been solved.
