### ISSUE TITLE
[BUG] Shoot & Pass Button

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#17]
Hi Team,

We just got a bug report about shoot button, the player was play normally and the shot button suddenly change like the attachment below.

Our team also have try several time in playing but we never occured this bug.

Thanks,
Erwin
![3650d6a0-1b9e-48ba-8a88-e8dd5ece8243](https://user-images.githubusercontent.com/31034413/31606154-87d6416e-b292-11e7-80d0-a957312ac6a4.jpg)

**Comment by ErwinGL1** [comment]
hi, we got so many report about this bug, here is another video about it, anyone can help to explain why this occured?


[WhatsApp Video 2017-10-27 at 09.46.49.mp4.zip](https://github.com/SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA/files/1420797/WhatsApp.Video.2017-10-27.at.09.46.49.mp4.zip)

**Comment by cgore16** [comment]
Hi

This happens when the game crashes at the start of matches for some reason, we will investigate this now and see if we can get a fix out.

Cheers
Chris



-----Original Message-----

**Comment by MattheusRossopIII** [comment]
I cannot recreate this issue, despite trying on accounts that have had this issue.  I think perhaps it was an issue with static player data in the database that has since been resolved?

**Comment by ErwinGL1** [comment]
I also think so, I will close this and re-open if there are any report about this again in future

Thanks Matt

**Comment by ErwinGL1** [comment]
Hi team, this issue is still appeared on new version..

Even if you cannot reproduce this, can't we just remove that shot + pass button from the game so it won't appear and whenever the game crash, we just need to close the game?

![2b71a320-110f-45c3-8438-9bd585e85018](https://user-images.githubusercontent.com/31034413/32872501-a71e2a02-cab9-11e7-94e1-9549e7e95eee.jpg)

**Comment by farahliany** [comment]
This issue has been solved, now.
