### ISSUE TITLE
Pop-up ads

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#18]
Hello team,

We would like to request a pop-up ads for the first time login in that day, so every player when they open the game for first time in that day, the pop-up will appear and can re-direct to a news / article that we have created.

If it possible please add this to the dashboard, so our team can upload the image for ads and also write the news for the content.

Thanks,
Erwin

**Comment by ErwinGL1** [comment]
Hi team,

We need this feature in this week since our event will end soon..

**Comment by MattheusRossopIII** [comment]
An agreed solution has been introduced for v1.0.17g, version code 47 of Android build.  When a new "Info Message" is posted from the dashboard, an info message modal is shown to the users.

**Comment by ErwinGL1** [comment]
Great, this will be our quick solution for now, I will discuss over with Chris or Andy about this again later

Thanks Matt!

**Comment by gloandrew** [comment]
Hi team, 

I'm attaching an example of what we've requested to be implemented into the game. 
From the video, you could see that there's a pop up notice when you first enter the game.
Players are then able to press on the specific notice that they want to read, and it will lead them to another page inside the game and they could read more information in regards to the notice.
Game: DigimonLinks
[https://drive.google.com/open?id=144saP-HEkNJdinnzSD3VP4SBn1Fy_u9_](https://drive.google.com/open?id=144saP-HEkNJdinnzSD3VP4SBn1Fy_u9_)

Here is another example. 
Game: Pocket Camp
[https://drive.google.com/open?id=1foedstlyb0pq1MAq-oYvNzbP1TRPx6gW](https://drive.google.com/open?id=1foedstlyb0pq1MAq-oYvNzbP1TRPx6gW)

Thank you!

**Comment by farahliany** [comment]
This feature has already added now.
