### ISSUE TITLE
Firebase Analytic Tracking in Next Build

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#2]
Hi Team,

Following up the latest discussion about Firebase Analytic Tracking in next build, and after GLO got the new link for dashboard : http://glo.soccermanagerarena.com from @cgore16 

We test and check it out, and we found everything we need for tracking are already inside this new dashboard. So for now, we can cancel this on the next build and we can discuss about the next update or enhancement in-game to help in promoting the game.

And I think if we need additional tracking, we can just improve and add it on the dashboard,, is that possible right?

Thanks

**Comment by MattheusRossopIII** [comment]
Yes, that sound right to me.

**Comment by ErwinGL1** [comment]
Okay great, thanks Matt..
