### ISSUE TITLE
[BUG] Invite Friend on Android Version

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#20]
Hi team,

The link for "Invite Friends" feature on Android Version for Soccer Manager Arena SEA still direct to Soccer Manager Arena, below I attached the video that show the issue.

Thanks.

[WhatsApp Video 2017-10-26 at 10.48.15.mp4.zip](https://github.com/SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA/files/1416938/WhatsApp.Video.2017-10-26.at.10.48.15.mp4.zip)

**Comment by MattheusRossopIII** [comment]
Fixed for v1.0.15g

**Comment by ErwinGL1** [comment]
thanks it's fixed
