### ISSUE TITLE
[BUG] Share Replay Match

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#21]
Hi Team,

We found another BUG, it was share replay in the game, when the player want to share a replay, they will got a message "Please check your internet connection and try again."

Here below is the attached video for the details.

[share replay bug.zip](https://github.com/SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA/files/1433526/share.replay.bug.zip)

**Comment by MattheusRossopIII** [comment]
Fixed for 1.0.15g

**Comment by ErwinGL1** [comment]
thanks, it's fixed
