### ISSUE TITLE
[BUG] Please check your internet connection and try again.

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#22]
Hi team, hope you quick check this bug and fix it soon, since yesterday the player face a trouble to play the game, whenever they want to join a league, leave the league, donate or request a player at league, they will got a message "Please check your internet connection and try again."

I think there are several issues at Soccer Manager Arena SEA's server for last several days, please fix this as soon as possible

Thanks

**Comment by MattheusRossopIII** [comment]
My colleague Mr Brennan has changed the AWS environment, this was the cause of the bug.

**Comment by ErwinGL1** [comment]
Okay, thanks Matt..

Cheers,

**Comment by ErwinGL1** [comment]
we got connection issues for android version :
- player cannot join a league
- player cannot quit from a league
- player cannot watch ads for bonus reward after the match
- player cannot request donate player
- player cannot donate player
- player cannot share a replay
- player cannot send a message on league

meanwhile on iOS is running well without all of those issues

**Comment by farahliany** [comment]
This problems are solved
