### ISSUE TITLE
[Error] Account Reset to Level 1 

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#23]
Hi team, 

There was an issue with the game where a number of players lost their progression and was brought back to level 1. Some of them said that they have already connected their Facebook to the game. 
The followings are their IGN
1. Devilbatz 
2. Muzamil
3. Zzzz
4. Hadesh201
5. Dav
6. ¢нαяιѕѕє
Could you please check the account player log.

Thank you

**Comment by MattheusRossopIII** [comment]
- devilbatz shows as level 6, but can't see why this account doesn't work anymore
- muzamil has signed up without using Google Play Services, so getting their account reinstated is not possible
- zzzz and dav accounts show that they've not played any matches
- hadesh201 and ¢нαяιѕѕє show that they have 2 accounts, I think these accounts are the only ones fixable, trying to fix these now.

**Comment by ErwinGL1** [comment]
Thanks Matt, we have find a solution by transfer the old account to their new account
