### ISSUE TITLE
[BUG] Version 0.42 - Image Bug on Card

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#24]
Image bug where the characters in the card suddenly stack on top of each other.

Expected Result:
Image don't stack on top of each other.

Please refer to the image below for a sample to this problem.
![no 12 image bug on cards](https://user-images.githubusercontent.com/33440645/32598087-56d3e634-c56b-11e7-99e7-a921948e7c32.jpg)

Thank you.

**Comment by farahliany** [comment]
This issue has been solved.
