### ISSUE TITLE
[BUG] Version 0.42 - League Member Bug

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#25]
The number of members that is stated in the “League Info” and the number of members that are actually in the League, doesn’t match. Making other players unable to join the League.

Expected result : the number of members that viewed on the "League Info" are in sync with the  number of members inside the League

The image below is a sample to this problem
![no 13 league member bug](https://user-images.githubusercontent.com/33440645/32598179-9a68446c-c56b-11e7-9a14-1d21d69f8062.jpg)

Thank you.

**Comment by gloandrew** [comment]
Version 0.47

Hi team, 
In the latest version, the bug still persist.

![no 13 ver 0 47 league member bug](https://user-images.githubusercontent.com/33440645/32829336-5f4d350a-ca24-11e7-927a-626a96360cb8.jpeg)

Thank you

**Comment by farahliany** [comment]
This issue has been solved.
