### ISSUE TITLE
[BUG] Version 0.42 - Words Not Popping Out When You Press on The Tabs

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#26]
The Close button “X” and the title menu tab doesn’t appear when you first click on them. You have to click on them again, for the Close button and the title to appear. 
The problems also occurs when you click on "achievements", "exit menu", "leaderboard" and "replay match".

Please click the link below to see the problem. 

https://drive.google.com/open?id=1WpA2GWB7xDg0xriTKXuJvR7h0Vl8HpIu

Thank you.

**Comment by MattheusRossopIII** [comment]
Fixed for v1.0.17g, version code 47 of Android build.

**Comment by ErwinGL1** [comment]
Thanks Matt it's fixed now!
