### ISSUE TITLE
[BUG] Version 0.42 - Facebook Link

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#27]
Facebook link can’t be opened because the “Link Facebook” still connects to the old Facebook page, not the new one.
This is the new Facebook link, https://www.facebook.com/smarenasea/
Could you also change the "twitter" button to an"instagram" button.
This is the link to our Instagram, https://www.instagram.com/smarenasea/

The link below show the video to this problem,
Facebook:
https://drive.google.com/open?id=1lNUXOEwl2IqC_nbay2TeUl2hWNvcFA8m
Twitter:
https://drive.google.com/open?id=1drmiIJcgptvZ_iSOKfmI71I_GiFN_3Fg

Expected Result:
Facebook and Instagram links are linked in accordance to their respective links. 

Thank you.

**Comment by ErwinGL1** [comment]
Hi team, 
there also additional that need attention, it was at Settings > Like Us and Follow Us need to replace with new link too..

Thanks

**Comment by farahliany** [comment]
This issue has been solved now.
