### ISSUE TITLE
[BUG] Version 0.42 - Trophy Information Bug

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#29]
The “Trophy” information is stuck after you click on it even when you tried moving to the next page.

Please click on the link below to see the video to this problem,
https://drive.google.com/open?id=1N4JdhBIdRFSk18SnA42AvHw4bZq4MbBX

Thank you.

**Comment by MattheusRossopIII** [comment]
Cannot recreate this bug, changed priority level to minor as it's not a critical bug.

**Comment by gloandrew** [comment]
Version 0.47

Hi team, 

Just want to inform that the bug kind of escalates now to the cash and coins information tab also getting stuck on the game and not closing properly. 
Also when you go to the Attribute Page, the numbers on the attributes stacks on top of each other.

How to recreate the bug:
Force close the game and open it again

Expected result:
The information tabs closing properly and the numbers on the attributes page doesn't stack on top of each other.

![no 17 ver 0 47 trophy information bug](https://user-images.githubusercontent.com/33440645/32830396-a23c4678-ca27-11e7-9ce6-50ac72c81005.jpeg)

**Comment by farahliany** [comment]
This issue has been solved.
