### ISSUE TITLE
[BUG] Version 0.42 - Tabs Overlapping Each Other

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#30]
The tabs are overlapping each other because they don't close properly.

Please look at the videos below to see the problem,
https://drive.google.com/open?id=1YV6ssk5ALVVOClWpp-XwbmZxEt9Ch-Rr
https://drive.google.com/open?id=1Q-h-bFf-xH9hzEYbe0uSfvgECtHCfd5_

Expected Result:
Tabs do not overlap each other. So when you close a tab, it'll close and not overlap each other.

Thank you.

**Comment by farahliany** [comment]
This issue has been solved.
