### ISSUE TITLE
[ERROR 500] Backend Dashboard Error

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#31]
Soccer Manager Arena SEA backend dashboard is not able to assign another players as the new League President/Vice President. We are also not able to change a League’s name.
When you click on it, it’ll bring us to another page saying “The page isn’t working, glo.soccermanagerarena.com is currently unable to handle this request. HTTP ERROR 500”

Error shown in video below:
https://drive.google.com/open?id=1z2jMFFBy0UAwTK5lqfo4dWGokeFQNfF0

There’s also a League that’s called “Malaysian Cup” where we are able to see the League in-game but when we want to check it through the dashboard, we can’t find it. 
View from phone in-game:
![no 19 backend dashboard error 1](https://user-images.githubusercontent.com/33440645/32938854-269c0ac8-cbb0-11e7-97a4-50c81f50cc5c.jpeg)

View from backend dashboard:
![no 19 backend dashboard error 2](https://user-images.githubusercontent.com/33440645/32938851-2444c0b2-cbb0-11e7-8296-3fc22d1a4102.png)

**Comment by farahliany** [comment]
This issue has been solved.
