### ISSUE TITLE
In-game inbox messaging

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#34]
Hi Team, 

We would like to request an in-game inbox messaging so that we'll be able to send direct messages or items to players. 
Please refer to the videos below for examples.

[https://drive.google.com/open?id=1yEqx3iu9WSBWLWrC0zvv6xRen-zbp9np](https://drive.google.com/open?id=1yEqx3iu9WSBWLWrC0zvv6xRen-zbp9np)

[https://drive.google.com/open?id=1hdZ-GVUWUWX9wzbwcO01vK3Okwajk0Ih](https://drive.google.com/open?id=1hdZ-GVUWUWX9wzbwcO01vK3Okwajk0Ih)

Thank you!

**Comment by farahliany** [comment]
feature now available in game
