### ISSUE TITLE
Share Match Replays Error

### ISSUE THREAD

**Issue by gloandrew** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#36]
Hi team, 

Players have been reporting that they are not able to share match replays to the League.
Please refer to the video below to view the error:
[https://drive.google.com/open?id=1Cmo8I4xJxvTwTUVJ-bQZupfg5ANDkTEW](https://drive.google.com/open?id=1Cmo8I4xJxvTwTUVJ-bQZupfg5ANDkTEW)

Thank you.

Regards, 
Andrew

**Comment by farahliany** [comment]
This issue has been solved now.
