### ISSUE TITLE
[BUG] iOS in-app purchases

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#4]
Hi Team, 

We got several reports from player from iOS, they made a purchase but their didn't get their credit. 

Please investigate and fix this soon.. 

Thanks, 
Erwin

**Comment by christianpatar** [comment]
Hi team,
I also add a video for you to help you investigate this issue.

thanks.
Christian

[VID-20170826-WA0004.mp4.zip](https://github.com/SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA/files/1253655/VID-20170826-WA0004.mp4.zip)

**Comment by MattheusRossopIII** [comment]
Hi Christian, I've just spoken to my colleague who has also seen this exact issue on our version of the game.  Can you tell me if it happens everytime, or is it an intermittent issue?

**Comment by christianpatar** [comment]
It happens everytime. currently the issue still happenning, I just tested it now.

**Comment by MattheusRossopIII** [comment]
My colleague needs to know if you get the credits when the app is restarted.

**Comment by ErwinGL1** [comment]
no. we dont get the credits even after the app has been restarded. the transaction also are not recorded on glo.soccermanagerarena.com and iTunes Connect

**Comment by MattheusRossopIII** [comment]
I'm trying to create a build for TestFlight with additional debugging in to help resolve this issue.  The "GameLevelOne" provisioning profile is "invalid", which is preventing me from creating a signed build to test with.  Can you guys sort out this profile for me?  Link: [https://developer.apple.com/account/ios/profile/production](https://developer.apple.com/account/ios/profile/production)

**Comment by MattheusRossopIII** [comment]
I believe that I've fixed the issue on a development build, I'll need to have the "GameLevelOne" provisioning profile fixed by GL1 before i can upload a build to TestFlight etc.

**Comment by ErwinGL1** [comment]
Thanks Matt, currently i'm still on my way back to office, I will immediately fix the provisioning profile for iTunes after I arrive at office..

**Comment by MattheusRossopIII** [comment]
Excellent, thanks!

**Comment by ErwinGL1** [comment]
Hi Matt, I just activate the provisioning profile for GameLevelOne iOS distribution, now you can try upload the build for TestFlight

**Comment by ErwinGL1** [comment]
Hi Matt, below I attach the certificate in format .p12 by your request yesterday


[GameLevelOne Certificate.zip](https://github.com/SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA/files/1266052/GameLevelOne.Certificate.zip)

**Comment by MattheusRossopIII** [comment]
Hi Erwin, can we close this one now?

**Comment by ErwinGL1** [comment]
Yes, Thanks Matt

This issue has been fixed by the latest build 1.4.1 that uploaded by Matt by Friday, September 1, 2017
