### ISSUE TITLE
[BUG] Loading Stuck at 2% for Android

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#5]
Hi Team, 

We have a lot of player that stuck at 2% loading, this occured when they finish tutorial and cannot input Club Name and try reset the app, and after that they stuck at 2%. And mostly occured on the player that lost connection when playing tutorial,  and after they re-connect, they also stuck at 2%.

Do you face this issue in Europe Server too?

**Comment by christianpatar** [comment]
Hi Team,

Adding to this issue, there aren't any notification that notify users that their connection is bad when the loading occurs. compared to "clash royale" that notify users that their connection was lost, we dont have this feature. so people think that their phone is the one that dont have any problem, while actually their connection is the one that disconnected.

I also upload here a video to help you investigate this issue. in this video, I tried to log in clash royale and SM Arena without any connection to see the notification sign. and in the end, i tried to reconnecting the disconnected connection on clash royale after I reconnected my wifi.  

[loading stuck no connection.mp4.zip](https://github.com/SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA/files/1255880/loading.stuck.no.connection.mp4.zip)

**Comment by MattheusRossopIII** [comment]
I have reproduced this issue, I will implement a fix for it this week and will notify you with a build to test.

**Comment by MattheusRossopIII** [comment]
Fixed in build 1.0.13g, please can you look at this build on your Alpha channel?

**Comment by ErwinGL1** [comment]
Thanks Matt, it solved now..
