### ISSUE TITLE
[BUG] Character Sprite and Stuck at Tutorial Loading

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#6]
Hi Team, 

We just got another bug report for iOS user.. 

They got bug after install and run the game for first time, it on pack opening animation and stuck on Tutorial loading

**Comment by christianpatar** [comment]
Hi team,
I add the video here to help you investigate this issue

[bug shadow.mp4.zip](https://github.com/SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA/files/1255730/bug.shadow.mp4.zip)

**Comment by MattheusRossopIII** [comment]
I have seen this exact issue before, I believe that Chris G will know the cause. @cgore16

**Comment by MattheusRossopIII** [comment]
The issue shown in the video occurs when there is no internet connectivity.  We will improve the handling of this scenario and for when there is no connectivity during start up of the app.

**Comment by farahliany** [comment]
This issue has been solved now.
