### ISSUE TITLE
[BUG] Free Champions Pack from Facebook & Friends

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#7]
Hi Team,

Today we got report about Champions Pack from Facebook, when they want to get the Champion Pack, they directed to Facebook Login, but after login they cannot claim or even see their Friends from Facebook.

Can you investigate and check this problem?

Thanks!

**Comment by ErwinGL1** [comment]
UPDATE:
the latest build 1.4.1 for iOS is released and for this new version, the Champion Pack is finely working, this issue only occured on the Android version.

**Comment by MattheusRossopIII** [comment]
Fixed in build 1.0.13g, please can you look at this build on your Alpha channel?

**Comment by ErwinGL1** [comment]
Thanks Matt, I already tried it and it's work now!
