### ISSUE TITLE
[BUG] Friendly Match on League

### ISSUE THREAD

**Issue by ErwinGL1** [SoccerManagerArenaSEA/Soccer-Manager-Arena-SEA#8]
Hi,

We just realize that the friendly match feature on League is not working in this Singapore Version

Can you try investigate and check it out?

**Comment by MattheusRossopIII** [comment]
The Singapore AWS PHP was a different version to the European PHP.  Some of the code that handles friendlies was not supported by the Singapore version.  Should be able to close this now, as a server-side fix has been uploaded.

**Comment by ErwinGL1** [comment]
Thanks Matt!
